### ISSUE TITLE
onChange and onBlur validation errors should prevent submission of form

### ISSUE THREAD

**Issue by crutchcorn** [TanStack/form#490]
Currently, when using a field with:

```tsx
<Field onChange={z.string().min(1)}>
```

When the user submits the form, it does not show a form error on submit. This causes headaches currently as it makes things harder to workflow properly.

**Comment by vikaskumar89** [comment]
Hey @crutchcorn 
Can you assign this to me please

**Comment by I-MirzaBaig** [comment]
Can you aasign this issue to me?

**Comment by vikaskumar89** [comment]
hey @I-MirzaBaig 
I am working on this. Could you pick any other open issue.

**Comment by I-MirzaBaig** [comment]
@vikaskumar89 Alright!

**Comment by vikaskumar89** [comment]
Hey @crutchcorn 
The root cause of this error is because we have defined `undefined` for the `submit` cause that leads to validateSync returning early and not executing any `onBlur/onChange` validation.

One solution that comes to my mind is in case of `submit` cause, we can execute either `onChange` or `onBlur` validation(whichever is defined in the field) but this would lead to incorrect errorMap detail as the errorMapKey would be `submit` but the error would correspond to `onChange/onBlur`.

Do you have any alternate suggestion to fix this ?

**Comment by vikaskumar89** [comment]
Due to this errorMap array, we are facing this issue in https://github.com/TanStack/form/issues/486, as the errorMap is not clear after a valid value is entered.

**Comment by danteissaias** [comment]
Is there currently a workaround to this?

**Comment by eastack** [comment]
I'm not sure when the maintainer will merge this, but is there any other way we can work around these issues temporarily?
