### ISSUE TITLE
Form resets to default values on some re-renders

### ISSUE THREAD

**Issue by AshotN** [TanStack/form#742]
### Describe the bug

The form resets to it's default state when using a HTML `<dialog>` element.

You can force it to persist if you manually mark it `dirty` and `isTouched`

I'm not sure what else can cause the bug, surely it's not limited to a dialog

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/eloquent-farrell-rdqdnz?file=%2Fsrc%2FApp.js%3A52%2C39

### Steps to reproduce

Click "Open Dialog"

To cause the issue, press "Set Data" and once you close the dialog, the inputs will clear.

The "Set Data Dirty" will persist, until the dialog is re-opened. Then the form resets again anyway

### Expected behavior

I would expect the form default data to only be set on initial render

### How often does this bug happen?

Every time

### Platform

- OS: Mac OS
- Browser: Firefox

### TanStack Form adapter

react-form

### TanStack Form version

0.21.0

**Comment by crutchcorn** [comment]
We had a few issues causing this before, but 0.24.0 _technically_ makes this API work.

However, you'll still find a bug without `{touch: true}` on `setFieldValue` - like so:

```
form.setFieldValue("firstName", val.firstName, { touch: true });
```

This option is a scourge (my fault) on TanStack Form and we're removing it (making it `true` default and renaming the property to opt-out, not opt-in behavior).

The fix for now is to:

- Update to `0.24.0`
- Move all `setFieldValue`s to `{touch: true}`

Closing, since we know about `touch: true` removal and are tracking here:

https://github.com/TanStack/form/issues/660

**Comment by AshotN** [comment]
Appreciate the update and everything Tanstack does. Excited for form to become stable.
